[vpnconfig1]
  username="neuron-lab-user-1"
  password="KLz3Znea#RKK"
[vpnconfig2]
  username="neuron-lab-user-2"
  password="KLz3Znea#RKK"
[vpnconfig3]
  username="neuron-lab-user-3"
  password="KLz3Znea#RKK"
[vpnconfig4]
  username="neuron-lab-user-4"
  password="KLz3Znea#RKK"
[vpnconfig5]
  username="neuron-lab-user-5"
  password="KLz3Znea#RKK"
[vpnconfig6]
  username="neuron-lab-user-6"
  password="KLz3Znea#RKK"
[vpnconfig7]
  username="neuron-lab-user-7"
  password="KLz3Znea#RKK"
[vpnconfig8]
  username="neuron-lab-user-8"
  password="KLz3Znea#RKK"
[vpnconfig9]
  username="neuron-lab-user-9"
  password="KLz3Znea#RKK"
[vpnconfig10]
  username="neuron-lab-user-10"
  password="KLz3Znea#RKK"



